import axiosClient from '../api/axiosClient';

export const getSlider = () => axiosClient.get('/sliders');
export const getCommunitiesMemberListing = () => axiosClient.get('/communities');
export const getMembersListing = () => axiosClient.get('/members');
export const getVillagesListing = () => axiosClient.get('/villages');
export const getNewsListing = () => axiosClient.get('/news');
export const getAboutUsDataListing = () => axiosClient.get('/about');
export const getBusinesListing = () => axiosClient.get('/businesses?search=approved');
export const getFAQsListing = () => axiosClient.get('/faqs');
export const postOrderCreate = (payload) => axiosClient.post('/create-order', payload);
export const registerUser = (payload) => axiosClient.post('/createMember', payload);
export const verifyPayment = (payload) => axiosClient.post('/verify-payment', payload);
export const loginMember = (payload) => axiosClient.post('/loginMember', payload);
export const checkExitMember = (payload) => axiosClient.post('/checkExitMember', payload);
export const resetPassword = (payload) => axiosClient.post('/reset-password', payload);
export const verifyOtp = (payload) => axiosClient.post('/verifyOtp', payload);
export const changePassword = (payload) => axiosClient.post('/change-password', payload);
export const getPerents = (id) => axiosClient.get(`/parents/${id}`);
export const createFamilyMember = (payload) => axiosClient.post('/createFamilyMember', payload, { headers: { 'Content-Type': 'multipart/form-data' } });
export const editMember = (id) => axiosClient.get(`/editMember/${id}`);
export const updateMember = (id, payload) => axiosClient.put(`/updateMember/${id}`, payload, { headers: { 'Content-Type': 'multipart/form-data' } });
export const deleteMember = (id) => axiosClient.delete(`/deleteMember/${id}`);
export const familyList = (id) => axiosClient.get(`/familyList/${id}`);
export const createBusiness = (payload) => axiosClient.post('/createBusiness', payload, { headers: { 'Content-Type': 'multipart/form-data' } });
export const getSubscriptions = () => axiosClient.get('/subscriptions');
export const getBussinessListing = (id) => axiosClient.get(`/ownBussiness/${id}`);
export const getTermsAndCondition = () => axiosClient.get('/terms');
export const getEvents = () => axiosClient.get('/events');
export const getEventDetails = (id) => axiosClient.get(`/editEvent/${id}`);
export const getSettings = (key) => axiosClient.get(`/settings?key=${key}`);
export const createEvent = (payload) => axiosClient.post('/createEvent', payload, { headers: { 'Content-Type': 'multipart/form-data' } });
export const getMyEvents = (id) => axiosClient.get(`/events`);
export const getMemberDetails = (id) => axiosClient.get(`/memberDetails/${id}`);
